### PR TITLE
Fix the Maven-in-Maven call on Windows"

### LINKED ISSUE #49: Can't use the CLI on Windows
It seems, that on Windows the parent environment is not forwarded to the spawned `mvn` process, like it is on Linux.
So that I get the following error, when I try to build a simple custom war configuration:
```
Exception in thread "main" java.io.IOException: Cannot run program "mvn" (in directory "tmp\prebuild"): CreateProcess error=2, Das System kann die angegebene Datei nicht finden
	at java.lang.ProcessBuilder.start(Unknown Source)
	at io.jenkins.tools.warpackager.lib.util.SystemCommandHelper.runFor(SystemCommandHelper.java:29)
	at io.jenkins.tools.warpackager.lib.util.SystemCommandHelper.processFor(SystemCommandHelper.java:20)
	at io.jenkins.tools.warpackager.lib.util.MavenHelper.run(MavenHelper.java:60)
	at io.jenkins.tools.warpackager.lib.util.MavenHelper.run(MavenHelper.java:42)
	at io.jenkins.tools.warpackager.lib.impl.Builder.build(Builder.java:142)
	at io.jenkins.tools.warpackager.cli.Main.main(Main.java:56)
Caused by: java.io.IOException: CreateProcess error=2, Das System kann die angegebene Datei nicht finden
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 7 more
```
On Linux it works out of the box.

I can workaround this on windows, by calling the inner `mvn` command by myself:
```
cd tmp\prebuild
mvn package
```

### PR DESCRIPTION
**Pull request by kunerd**
Fixes #49

### CODE REVIEW

File: custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/util/MavenHelper.java [hunk 1]
```diff
@@ -32,9 +32,11 @@
     private static final Logger LOGGER = Logger.getLogger(MavenHelper.class.getName());
 
     private Config cfg;
+    private String mvnCommand;
```
Comment (oleg-nenashev) [inline custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/util/MavenHelper.java]: can be actually a singleton so that you do not need to reinit it for each `MavenHelper` instance. But it should be probably be a singleton as well so 🤷‍♂️

File: custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/util/MavenHelper.java [hunk 2]
```diff
@@ -63,6 +67,17 @@ public int run(File buildDir, boolean failOnError, String ... args) throws IOExc
         return runFor(buildDir, callArgs.toArray(args));
     }
 
+    private String getOsSpecificMavenCommand() {
+        String mvnCmd = "mvn";
+
+        String osName = System.getProperty("os.name");
+        if(osName.toLowerCase().compareTo("windows") == 0) {
```
Comment (oleg-nenashev) [inline custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/util/MavenHelper.java]: In edge cases it may be null. 

Maybe this one?

```
if(osName != null && os.toLowerCase().contains("windows")) { 
```

File: custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/util/MavenHelper.java (hunk 1 above)
Comment (kunerd) [reply custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/util/MavenHelper.java]: Hope my current solution is the right way to do it in Java, haven't done any serious Java work for about 5 years or so.

File: custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/util/MavenHelper.java (hunk 2 above)
Comment (kunerd) [reply custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/util/MavenHelper.java]: fixed

File: custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/util/MavenHelper.java (hunk 1 above)
Comment (oleg-nenashev) [reply custom-war-packager-lib/src/main/java/io/jenkins/tools/warpackager/lib/util/MavenHelper.java]: Let's keep it as is, can be refactored later
